### ISSUE TITLE
能添加更多实例吗？

### ISSUE THREAD

**Issue by xiezhuojin** [zyfjeff/C-HOW-TO#1]
我是C语言的新手，之前学的是python，想更多的了解一些高级语言的底层实现，你的教程对我来说很有用，但是我还想了解比如像垃圾回收这样的功能和面向对象，我可以到哪学习呢？

**Comment by zyfjeff** [comment]
@xiezhuojin 可以先看下垃圾回收的一些基本原理，然后分析下python的垃圾回收是如何做的，推荐一本书
https://book.douban.com/subject/26821357/
